services:
  backend:
    build: ./backend
    container_name: app_backend
    platform: linux/amd64
    ports:
      - 3001:3001
    volumes:
      - ./backend:/app/back
    depends_on:
      logDb:
        condition: service_healthy
      db:
        condition: service_healthy
    environment:
      - PORT=3001
      - DB_USER=root
      - DB_PASS=20142017
      - DB_HOST=db
      - DB_NAME=ToDoList
      - DB_PORT=3306
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"] # Caso utilize outra porta interna para o back, altere ela aqui também
      timeout: 10s
      retries: 5

  frontend:
    build: ./frontend
    container_name: app_frontend
    platform: linux/amd64
    ports:
      - 3000:3000
    depends_on:
        backend:
          condition: service_healthy
    # Os `healthcheck` devem garantir que a aplicação
    # está operacional, antes de liberar o container
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]  # Caso utilize outra porta interna para o front, altere ela aqui também
      timeout: 15s
      retries: 7
    command: npm start

  db:
    image: mysql:8.0.21
    container_name: db
    platform: linux/amd64
    ports:
      - 3004:3306
    environment:
      - MYSQL_ROOT_PASSWORD=20142017
    restart: 'always'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"] # Deve aguardar o banco ficar operacional
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE # Deve omitir alertas menores

  